### ISSUE TITLE
Rerunning tests generates a new id everytime

### ISSUE THREAD

**Issue by PrashantAshok** [marko-js/testing-library#4]
### Details

This is basically what is in my template
```
<ebay-icon name="chevron-up"/>
```
First time it runs, it generates
```
<span
  class="icon icon--chevron-up"
  id="c3-3"/>
```
But the next time it runs, jest fails the tests and complains with the error that the id has changed. 
```
Received content doesn't match the file .html.
    - Snapshot
    + Received
    @@ -14,11 +14,11 @@
          </span>
          <span
            class="icon icon--chevron-up"
    -       id="c3-3"
    +       id="c2-3"
          />
```
### Expected Behavior
The ids shouldn't change between test runs

**Comment by mlrawlings** [comment]
Fixed in #5, released in `3.0.1`
